Create ur.json added Urdu
custom-components/ble_monitor pull request #1278
Opened 2023-12-30 16:21 UTC by yousaf465

added Urdu translations

2023-12-31 08:53 UTC, Ernst79 requested changes
Thanks, one comment, you missed one line I think, can you translate that as well?

2023-12-31 08:53 UTC, Ernst79 commented on custom_components/ble_monitor/translations/ur.json
> +          "use_median": "Use median instead of mean",
Shouldn’t this line be translated ?

2023-12-31 16:53 UTC, Ernst79 approved these changes
Thanks!

2023-12-31 16:54 UTC, merged

2024-01-01 03:24 UTC, yousaf465 commented
آپ کا بے حد شکریہ !!!